name: Code Quality Checks

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]

jobs:
  test:
    name: Unit testings with Python 3.12
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with pytest and coverage
      run: |
        pytest -v --tb=short --cov=src --cov-report=term-missing

  lint:
    name: Code Quality - Linting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with ruff
      if: always()
      run: |
        ruff check . --output-format=github

    - name: Format check with ruff
      if: always()
      run: |
        ruff format --check . --diff

    - name: Check for dead code with vulture
      run: |
        vulture src/ --min-confidence 80

    - name: Check docstring style with pydocstyle
      run: |
        pydocstyle src/

    - name: Type check with mypy
      run: |
        mypy src/calculator.py --strict

  security:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Security check with bandit
      run: |
        bandit -r src/ --severity-level medium --exclude tests/,scripts/

    - name: Check for known vulnerabilities with safety
      run: |
        safety check