name: Generate Documentation

on:
  push:
    branches: [ master, main ]
  pull_request:
    types: [ closed ]
    branches: [ master, main ]

jobs:
  docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install sphinx sphinx-rtd-theme

    - name: Generate HTML docs from docstrings
      run: |
        mkdir -p docs/source
        python scripts/generate_docs.py
        sphinx-build -b html docs/source docs/build/html

    - name: Copy built docs to repo docs directory
      run: |
        mkdir -p docs/html
        cp -r docs/build/html/* docs/html/

    - name: Commit and push generated docs
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add docs/html/
        git commit -m "docs: auto-generate documentation from docstrings" || true
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}

    - name: Upload documentation artifact
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/build/html/
